spring:
  application:
    name: spring-security

mongo:
  connectionString: ${connection_string}
  db_name: spring-security

app:
  security:
    jwt:
      secret: aWlnY3BjYzc4NDk0OGpkZW5TRkhHNTY4dzg4MzczZ3dndXkzZ3VnZQ==
      expirationMin: 120
      refreshToken_expirationMin: 10080